config/routes.rb
Rails.application.routes.draw do

  resources :service_reminders
  resources :pdf_types
  resources :locations
  resources :reports
  resources :logs
  resources :detail_requests
  resources :equipment_pdfs
  mount EpiCas::Engine, at: "/"
  devise_for :accounts

  get 'finances/index'
  # get 'finances/show'

  resources :accounts do
    post :search, on: :collection
  end
  resources :audits
  resources :pdfs do
    get :show_pdf, on: :member
  end
  resources :equipment do
    get :show_image, on: :member
    post :search, on: :collection
  end
  resources :pdfs do
    post :search, on: :collection
  end
  resources :locations do
    post :search, on: :collection
  end

  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "pages#home"

  #get :splash, to: 'pages#splash'
  #get :borrowing, to: 'pages#borrowing'
  #get :returning, to: 'pages#returning'
  #get :home, to: "pages#home"
  get :view_items, to: 'equipment#index'
  get :new_equipment, to: 'equipment#new'
  # get :add_equipment, to: 'pages#add'
  # get :view_account_archive, to: 'pages#view_account_archive'
  # get :view_item_archive, to: 'pages#view_item_archive'
  # get :view_pdf, to: 'pages#view_pdf'
  # get :tables, to: 'pages#tables'
  # get :user, to: 'pages#user'
  # get :item, to: 'pages#item'
  # get :add_account, to: 'pages#add_account'
  # get :view_laboratories, to: 'pages#view_laboratories'
  # get :laboratory, to: 'pages#laboratory'
  get 'details/new/:id', to: 'details#new'
  get 'details/toggle_is_archived/:id', to: 'details#toggle_is_archived'
  get 'detail_requests/approve/:id', to: 'detail_requests#approve'
  get 'detail_requests/approve_equipment/:id', to: 'detail_requests#approve_equipment'
  get 'detail_requests/remove_equipment/:id', to: 'detail_requests#deny_equipment'
  get 'detail_requests/approve_extension/:id', to: 'detail_requests#approve_extension'
  get 'detail_requests/reject_extension/:id', to: 'detail_requests#reject_extension'
  get 'reports/new/:a_id', to: 'reports#new'
  get 'reports', to: 'reports#index'
  get 'audits/new/:s_id', to: 'audits#new'
  get 'trainings/add_equipment/:p_id/:t_id', to: 'trainings#add_equipment'
  get 'trainings/add_equipment/:p_id', to: 'trainings#add_equipment'
  get 'trainings/add_account/:a_id/:t_id', to: 'trainings#add_account'
  get 'trainings/add_account/:a_id', to: 'trainings#add_account'
  get 'trainings/remove_account/:id', to: 'trainings#remove_account'
  get 'trainings/remove_equipment/:id', to: 'trainings#remove_equipment'
  get 'pdfs/add_equipment/:e_id/:p_id', to: 'pdfs#add_equipment'
  get 'pdfs/add_equipment/:e_id', to: 'pdfs#add_equipment'
  get 'finances', to: 'finances#index'do
    post :search, on: :collection
  end
  resources :trainings
  resources :details
  get 'finances/:p_id', to: 'finances#index'
  get 'finances/:p_id/:s_id', to: 'finances#index'
  get :backup, to: 'backup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
# == Schema Information
#
# Table name: trainings
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Training < ApplicationRecord
  has_many :accounts_trainings
  has_many :equipment_trainings
  has_many :accounts, through: :accounts_trainings
  has_many :equipment, through: :equipment_trainings
  validates :name, :presence => true
  validates :description, :presence => true
  
  def self.to_csv(make)
    attributes = %w{id name description created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      Training.all.each do |e|
        csv << attributes.map{ |attr| e.send(attr) }
      end
    end
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  def remove_account
    puts "1"
    account_training = AccountsTraining.find(params[:id])
    Log.create(account_id: current_account[:id], action: "Removed #{account_training.training.name} from account ID: #{account_training.account_id}")
    puts "2"
    AccountsTraining.destroy(params[:id])
    puts "3"
    redirect_to "/accounts/#{account_training.account_id}", notice: 'Training was successfully removed.'
  end

  def remove_equipment
    puts "1"
    equipment_training = EquipmentTraining.find(params[:id])
    Log.create(account_id: current_account[:id], action: "Removed #{equipment_training.training.name} from equipment ID: #{equipment_training.equipment_id}")
    puts "2"
    EquipmentTraining.destroy(params[:id])
    puts "3"
    redirect_to "/equipment/#{equipment_training.equipment_id}", notice: 'Training was successfully removed.'
  end

  def add_equipment
    if params[:t_id]
      Log.create(account_id: current_account[:id], action: "Added #{Training.find(params[:t_id]).name} training to equipment: #{Equipment.find(params[:p_id]).name}")
      EquipmentTraining.create(equipment_id: params[:p_id], training_id: params[:t_id])
      redirect_to "/equipment/#{params[:p_id]}", notice: 'Training was successfully created.'
    else
      @trainings = Training.all - Equipment.find(params[:p_id]).trainings
    end
  end

  def add_account
    if params[:t_id]
      Log.create(account_id: current_account[:id], action: "Added #{Training.find(params[:t_id]).name} training to account ID: #{params[:a_id]}")
      AccountsTraining.create(account_id: params[:a_id], training_id: params[:t_id])
      redirect_to "/accounts/#{params[:a_id]}", notice: 'Training was successfully created.'
    else
      @trainings = Training.all - Account.find(params[:a_id]).trainings
    end
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  def create
    @training = Training.new(training_params)

    if @training.save
      redirect_to @training, notice: 'Training was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trainings/1
  def update
    if @training.update(training_params)
      redirect_to @training, notice: 'Training was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trainings/1
  def destroy
    @training.destroy
    redirect_to trainings_url, notice: 'Training was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def training_params
      params.require(:training).permit(:name, :description)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.haml
= simple_form_for(@training) do |f|
  = f.error_notification

  .form-inputs.form-horizontal
    .form-group
      .control-label.col-sm-4
        = f.label "Name: "
      .col-sm-8
        = f.input :name, :label => false
    .form-group
      .control-label.col-sm-4
        = f.label "Description: "
      .col-sm-8
        = f.input :description, :label => false

  .form-actions
    .form-group
      .col-sm-12
        = f.button :submit

app/views/trainings/add_account.html.haml
.container
  %h1 Add training to account ID: #{params[:a_id]}

  %table.table-hover
    %thead
      %tr
        %th Training
    %tbody
      - (@trainings).each do |trains|
        %tr{:onclick => "window.location='/trainings/add_account/#{params[:a_id]}/#{trains[:id]}';"}
          %td #{trains.name}

app/views/trainings/add_equipment.html.haml
.container
  %h1 Add training to product ID: #{params[:p_id]}
  %a.btn{:href => new_training_path, :role => "button"} New Training
  %table.table-hover
    %thead
      %tr
        %th Training
    %tbody
      - (@trainings).each do |trains|
        %tr{:onclick => "window.location='/trainings/add_equipment/#{params[:p_id]}/#{trains[:id]}';"}
          %td #{trains.name}

app/views/trainings/edit.html.haml
- content_for :title, "Training"
.container
  %h1 Editing training
  .row
    .col-sm-8.col-sm-offset-2
      = render 'form'
  %br
  .row
    -# = link_to 'Show', @training
    %a.btn{:href => "/trainings/#{@training.id}", :role => "button"} Show
    -# = link_to 'Back', trainings_path
    %a.btn{:href => "/trainings", :role => "button"} Back

app/views/trainings/index.html.haml
- content_for :title, "TRAININGS"
.container
  %h1 Training

  %table.table-hover
    %thead
      %tr
        %th{:style => "width: 25%"} Trainin ID.
        %th{:style => "width: 25%"} Name
        %th{:style => "width: 25%"} Description
        %th{:style => "width: 8%"}
        %th{:style => "width: 8%"}
        %th{:style => "width: 8%"}
    %tbody
      - @trainings.each do |train|
        %tr
          %td #{train[:id]}
          %td #{train.name}
          %td #{train.description}
          %td= link_to 'Show', train
          %td= link_to 'Edit', edit_training_path(train)
          %td= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' }

  %a.btn{:href => new_training_path, :role => "button"} New Training

app/views/trainings/new.html.haml
- content_for :title, "New Training"
.container
  %h1 New Training
  .row
    .col-sm-8.col-sm-offset-2
      = render 'form'
  %br
  .row
    -# = link_to 'Back', trainings_path
    %a.btn{:href => "/trainings", :role => "button"} Back

app/views/trainings/show.html.haml
- content_for :title, "Training Items"
.container
  %p#notice= notice
  %h1 #{@training.name}
  %b Description:
  %p #{@training.description}

  -# = link_to 'Edit', edit_training_path(@training)
  %a.btn{:href => "/trainings/#{@training.id}/edit", :role => "button"} Edit
  -# = link_to 'Back', trainings_path
  %a.btn{:href => "/trainings", :role => "button"} Back