config/routes.rb
Rails.application.routes.draw do

  resources :service_reminders
  resources :pdf_types
  resources :locations
  resources :reports
  resources :logs
  resources :detail_requests
  resources :equipment_pdfs
  mount EpiCas::Engine, at: "/"
  devise_for :accounts

  get 'finances/index'
  # get 'finances/show'

  resources :accounts do
    post :search, on: :collection
  end
  resources :audits
  resources :pdfs do
    get :show_pdf, on: :member
  end
  resources :equipment do
    get :show_image, on: :member
    post :search, on: :collection
  end
  resources :pdfs do
    post :search, on: :collection
  end
  resources :locations do
    post :search, on: :collection
  end

  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "pages#home"

  #get :splash, to: 'pages#splash'
  #get :borrowing, to: 'pages#borrowing'
  #get :returning, to: 'pages#returning'
  #get :home, to: "pages#home"
  get :view_items, to: 'equipment#index'
  get :new_equipment, to: 'equipment#new'
  # get :add_equipment, to: 'pages#add'
  # get :view_account_archive, to: 'pages#view_account_archive'
  # get :view_item_archive, to: 'pages#view_item_archive'
  # get :view_pdf, to: 'pages#view_pdf'
  # get :tables, to: 'pages#tables'
  # get :user, to: 'pages#user'
  # get :item, to: 'pages#item'
  # get :add_account, to: 'pages#add_account'
  # get :view_laboratories, to: 'pages#view_laboratories'
  # get :laboratory, to: 'pages#laboratory'
  get 'details/new/:id', to: 'details#new'
  get 'details/toggle_is_archived/:id', to: 'details#toggle_is_archived'
  get 'detail_requests/approve/:id', to: 'detail_requests#approve'
  get 'detail_requests/approve_equipment/:id', to: 'detail_requests#approve_equipment'
  get 'detail_requests/remove_equipment/:id', to: 'detail_requests#deny_equipment'
  get 'detail_requests/approve_extension/:id', to: 'detail_requests#approve_extension'
  get 'detail_requests/reject_extension/:id', to: 'detail_requests#reject_extension'
  get 'reports/new/:a_id', to: 'reports#new'
  get 'reports', to: 'reports#index'
  get 'audits/new/:s_id', to: 'audits#new'
  get 'trainings/add_equipment/:p_id/:t_id', to: 'trainings#add_equipment'
  get 'trainings/add_equipment/:p_id', to: 'trainings#add_equipment'
  get 'trainings/add_account/:a_id/:t_id', to: 'trainings#add_account'
  get 'trainings/add_account/:a_id', to: 'trainings#add_account'
  get 'trainings/remove_account/:id', to: 'trainings#remove_account'
  get 'trainings/remove_equipment/:id', to: 'trainings#remove_equipment'
  get 'pdfs/add_equipment/:e_id/:p_id', to: 'pdfs#add_equipment'
  get 'pdfs/add_equipment/:e_id', to: 'pdfs#add_equipment'
  get 'finances', to: 'finances#index'do
    post :search, on: :collection
  end
  resources :trainings
  resources :details
  get 'finances/:p_id', to: 'finances#index'
  get 'finances/:p_id/:s_id', to: 'finances#index'
  get :backup, to: 'backup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/finances_controller.rb
require 'chartkick'
require 'date'
require 'time'

class FinancesController < ApplicationController

  #authorize_resource

  def index
    if !current_account.admin?
      redirect_to "/"
    end
    @equipment = Equipment.order(:id).all
    @detail = Detail.where(available: true).where(active: true)
    @data = {}

    if params[:s_id]
      details = Detail.where(equipment_id: params[:p_id]).where(detail_id: params[:s_id])
      detail = details.first
      reports = detail.reports

      # Info
      @data["detail"] = detail

      # Depreciation
      @data["depreciation"] = calcDepreciationValues(details, Date.today.next_year(-1), Date.today.next_year(1), "MONTHLY")

      # Life progress
      @data["life_progress"] = progress_life detail

      # Usage count
      audits = detail.audits


    elsif params[:p_id]
      equipment = Equipment.find(params[:p_id])
      details = equipment.detail
      report_id = details.map { |d| d.reports.pluck(:id) }.flatten
      reports = Report.where(id: report_id)

      # Info
      @data["equipment"] = equipment
      @totsAvailable = details.where(available: true).size
      @total = details.size

      # Depreciation
      @data["depreciation"] = calcDepreciationValues(details, Date.today.next_year(-1), Date.today.next_year(1), "MONTHLY")

      # Usage count
      audits_id = []
      details.each { |d| audits_id.concat d.audits.pluck(:id)}
      audits = Audit.where(id: audits_id)

      #Upcoming Expiries
      @data["upc_exp_tableB"] = upcoming_exp (Equipment.where(id: params[:p_id]))

    else
      details = Detail.all
      reports = Report.all

      # Upcoming Expiries
      # where is_exp returns true, return array of details
      # for single items, displays expiry date
      @data["upc_exp_tableA"] = upcoming_exp (Equipment.all)

      # Usage count
      audits = Audit.all

    end
    @data["tot_val"] = total_val (details)
    @data["usage_count"] = calcUsageValues(audits, Date.today.next_year(-1), Date.today, "MONTHLY")
    @data["report_rate"] = calc_report_values(reports, Date.today.next_year(-1), Date.today, "MONTHLY")

  end


  # POST /equipment/search
  def search
    # {"search" => {"name" => "some entered name"} }
    @equipment = Equipment.where("lower (name) LIKE :query", query: "%#{params[:search][:name].downcase}%").or(Equipment.where(id: params[:search][:name]))
    @detail = Detail.none
    @searched = true
    render :index
  end


  # Universal


  # Total value and current value
  # Total value
  def total_val (details)@s
    total_val = 0
    return details.each { |d| total_val += d.unit_cost }
  end

  # Depreciation formula
  def calcDepreciationValues(details, startDate, endDate, interval)

    depreciation_values = []

    details.each{ |d|
      hash = {}
      calcDates(startDate, endDate, interval).each { |date|
        hash[date] = calcDepreciation(d.unit_cost, d.created_at, d.life_expectancy, date)
      }
      depreciation_values.push({name: d.detail_id, data: hash })
    }

    return depreciation_values
  end

  def calcDepreciation(startPrice, startDate, expectancy, date)
    value = startPrice * (1 - ((date.to_time - startDate.to_time) / (31557600.0 / 12) / expectancy)).round(2)
    return (value > startPrice or value < 0) ? [] : value
  end

  # Usage rate
  def calcUsageValues(audits, startDate, endDate, interval)
    usage_rates = {}
    arr = calcDates(startDate, endDate, interval)
    for t in 0.. (arr.length - 2) do
      usage_rates[arr[t]] = usage(audits, arr[t], arr[t+1])
    end
    return usage_rates
  end
  def usage(audits, dateTime1, dateTime2)
    use_time = 0
    audits.where("created_at < ?", dateTime2).where("end_time > ?", dateTime1).find_each do |u|
      use_time += ([dateTime2, u.end_time].min).to_time.to_i - ([dateTime1, u.created_at].max).to_time.to_i
    end
    return use_time
  end

  # Failure rate
  def calc_report_values(reports, startDate, endDate, interval)
    rep_rates = {}
    arr = calcDates(startDate, endDate, interval)
    for t in 0.. (arr.length - 2) do
      rep_rates[arr[t]] = report_rate(reports, arr[t], arr[t+1])
    end
    return rep_rates
  end
  def report_rate(reports, dateTime1, dateTime2)
    return reports.where(:created_at => dateTime1..dateTime2).size
  end



  # General and Product


  # Upcoming Expiries
  def upcoming_exp equipments
    arr = []
    equipments.where(consumable: false).map{ |e| arr.concat e.detail.select{ |d| d.is_expired(3) }  }
    return arr
  end


  # Product and Serial


  # Equipment details
  # To be done in HAML file

  # Serial


  # Life timeline
  # Bootstrap progress bar - set progress to be (expiry date-date created).to_i / 100
  def progress_life detail
    return ((Date.today.to_time.to_f - detail.issue_date.to_time.to_f) / (detail.expire_date.to_time.to_f - detail.issue_date.to_time.to_f) * 100).round
  end

  # Vendor Info
  # to be done in HAML file


  # Calculate dates
  def calcDates (startDate, endDate, interval)
    arr = []
    while (startDate < endDate) do
      arr.push(startDate)
      case interval
      when "DAILY"
        startDate = startDate.next_day
      when "WEEKLY"
        startDate = startDate.next_day(7)
      when "MONTHLY"
        startDate = startDate.next_month
      else
        startDate = startDate.next_year
      end
    end
    arr.push(endDate)
    return arr
  end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/index.html.haml
- content_for :title, "VIEW_FINANCE"
.container
  %h1 View Finance

  - if @data["detail"]
    %h2 #{@data["detail"].equipment.name}
    %h4 Equipment ID: #{@data["detail"].equipment_id}, #{@data["detail"].detail_id}
    %p Unit cost: £#{@data["detail"].unit_cost}
    %p Availability: #{@data["detail"].available}
    %h4 Vendor Information
    %p Vendor Name: #{@data["detail"].vendor_name}
    %p Vendor Tel. No.: #{@data["detail"].vendor_contact}
    %p Purchase date: #{@data["detail"].purchase_date}
    %br

    -# Life progress bar
  - if @data["life_progress"]
    %h3 LifeSpan
    .progress
      .progress-bar.progress-bar-striped.bg-warning{:role => "progressbar", :style => "width: #{@data["life_progress"]}%"} #{@data["life_progress"]}%
    %p Expiry Date: #{@data["detail"].expire_date}
    %br

    -# Quantity available for product page
  - if @data["equipment"]
    %h2 #{@data["equipment"].name}
    -# %h4 Equipment ID: #{@data["equipment"].equipment_id}, #{@data["equipment"].detail_id}
    -# %p Unit cost: £#{ @data["equipment"].each {|d| d.unit_cost} }
    %p Quantity available: #{ @totsAvailable } / #{ @total }
    %br

  -# Usage
  - if @data["usage_count"]
    %h3 Usage
    #curve_chart{:style => "width: 900px"}
    = line_chart @data["usage_count"], xtitle: "Date", ytitle: "Time of Useage (seconds)"
    %br

  -# Report rate
  - if @data["report_rate"]
    %h3 Maintenance Reports Logged
    #curve_chart{:style => "width: 900px"}
    = line_chart @data["report_rate"], xtitle: "Date", ytitle: "Number of Reports Logged"
    %br

  -# Depreciation graph
  - if @data["depreciation"]
    %h3 Depreciation Graph
    = line_chart @data["depreciation"].map { |val|  {name: val[:name], data: val[:data]}}, xtitle: "Date", ytitle: "Value (£)"
    %br

  - if @data["upc_exp_tableB"]
    -# Upcoming Expiries table
    %h3 Upcoming Expiries
    %table.table-hover{}
      %thead
        %tr
          %th{:style => "width: 33%"} Serial ID
          %th{:style => "width: 33%"} Expiry Date
      %tbody
        - @data["upc_exp_tableB"].each do |equip|
          %tr{:onclick => "window.location='/finances/#{equip.equipment_id}/#{equip.detail_id}';"}
          %td #{equip.detail_id}
          %td #{equip.expire_date}
    %br

  - if @data["equipment"]
    -# Serial product list
    %h3 Items
    %table.table-hover{}
      %thead
        %tr
          %th{:style => "width: 33%"} Serial ID
          %th{:style => "width: 33%"} Name
          %th{:style => "width: 33%"} Availability
      %tbody
        - @data["equipment"].detail.each do |equip|
          %tr{:onclick => "window.location='/finances/#{equip.equipment_id}/#{equip.detail_id}';"}
            %td #{equip.detail_id}
            %td #{equip.equipment.name}
            %td #{equip.available}
    %br


  - if @data["upc_exp_tableA"]
    -# Upcoming Expiries table
    %h3 Upcoming Expiries
    %table.table-hover{}
      %thead
        %tr
          %th{:style => "width: 33%"} Product ID
          %th{:style => "width: 33%"} Serial ID
          %th{:style => "width: 33%"} Name
      %tbody
        - @data["upc_exp_tableA"].each do |equip|
          - if @searched
            %tr{:onclick => "window.location='/#{equip.equipment_id}';"}
              %td #{equip.equipment_id}
              %td #{equip.detail_id}
              %td #{@equipment.where(id: equip.equipment_id)[0].name}
          - else
            %tr{:onclick => "window.location='/finances/#{equip.equipment_id}/#{equip.detail_id}';"}
              %td #{equip.equipment_id}
              %td #{equip.detail_id}
              %td #{@equipment.where(id: equip.equipment_id)[0].name}
    %br

  - if params[:s_id]
    -# %button.btn.btn-warning{:href => "/finances/#{@data["detail"].equipment_id}", :type => "button"} Warning
    %a.btn.btn-warning{:href => "/finances/#{@data["detail"].equipment_id}", :role => "button"} Back to Equipment
    %a.btn.btn-warning{:href => "/equipment/#{@data["detail"].equipment_id}", :role => "button"} Equipment Items
  - if params[:p_id]
    - if not params[:s_id]
      %a.btn.btn-warning{:href => "/equipment/#{@data["equipment"].id}", :role => "button"} Equipment Items
    %a.btn.btn-warning{:href => "/finances", :role => "button"} Finance Overview

app/views/finances/show.html.haml
-# %p#notice= notice
-# -# .container
-# -#   %p
-# -#     %b item_id:
-# -#     = @equipment.detail_id
-# -#   %p
-# -#     %b Name:
-# -#     = @equipment.name
-# -#
-# -#   = link_to 'Edit', edit_equipment_path(@equipment)
-# -#   \|
-# -#   = link_to 'Back', equipment_index_path
-# - content_for :title, "EQUIPMENT"
-#
-#     %h1 View Finance
-#
-#     -# = simple_form_for:search, url: search_finances_path, method: :post do |f|
-#     -#   .small_container{:style => "background-color: transparent"}
-#     -#     = f.input :name, placeholder: 'Search Items', label: false
-#     -#   = f.submit 'Search', :class => "btn "
-#
-#     - if @data["detail"]
-#       %h2 #{@data["detail"].equipment.name}
-#       %h4 Equipment ID: #{@data["detail"].equipment_id}, #{@data["detail"].detail_id}
-#       %p Unit cost: £#{@data["detail"].unit_cost}
-#       %p Availability: #{@data["detail"].available}
-#       %h4 Vendor Information
-#       %p Vendor Name: #{@data["detail"].vendor_name}
-#       %p Vendor Tel. No.: #{@data["detail"].vendor_contact}
-#       %p Purchase date: #{@data["detail"].purchase_date}
-#       %br
-#
-#       -# Life progress bar
-#     - if @data["life_progress"]
-#       %h3 LifeSpan
-#       .progress
-#         .progress-bar.progress-bar-striped.bg-warning{:role => "progressbar", :style => "width: #{@data["life_progress"]}%"} #{@data["life_progress"]}%
-#       %p Expiry Date: #{@data["detail"].expiry_date}
-#       %br
-#
-#       -# Quantity available for product page
-#     - if @data["equipment"]
-#       %h2 #{@data["equipment"].name}
-#       -# %h4 Equipment ID: #{@data["equipment"].equipment_id}, #{@data["equipment"].detail_id}
-#       -# %p Unit cost: £#{ @data["equipment"].each {|d| d.unit_cost} }
-#       %p Quantity available: #{ @totsAvailable } / #{ @total }
-#       %br
-#
-#     -# Usage
-#     - if @data["usage_count"]
-#       %h3 Usage
-#       #curve_chart{:style => "width: 900px"}
-#       = line_chart @data["usage_count"], xtitle: "Date", ytitle: "Time of Useage (seconds)"
-#       %br
-#
-#     -# Report rate
-#     - if @data["report_rate"]
-#       %h3 Maintenance Reports Logged
-#       #curve_chart{:style => "width: 900px"}
-#       = line_chart @data["report_rate"], xtitle: "Date", ytitle: "Number of Reports Logged"
-#       %br
-#
-#     -# Depreciation graph
-#     - if @data["depreciation"]
-#       %h3 Depreciation Graph
-#       = line_chart @data["depreciation"].map { |val|  {name: val[:name], data: val[:data]}}, xtitle: "Date", ytitle: "Value (£)"
-#       %br
-#
-#     - if @data["upc_exp_tableE"]
-#       -# Upcoming Expiries table
-#       %h3 Upcoming Expiries
-#       %table.table-hover{}
-#         %thead
-#           %tr
-#             %th{:style => "width: 33%"} Serial ID
-#             %th{:style => "width: 33%"} Expiry Date
-#         %tbody
-#           - @data["upc_exp_tableE"].each do |equip|
-#             - if @searched
-#               %tr{:onclick => "window.location='#{equip.equipment_id}';"}
-#               %td #{equip.detail_id}
-#               %td #{equip.expiry_date}
-#             - else
-#               %tr{:onclick => "window.location='/finances/#{equip.equipment_id}/#{equip.detail_id}';"}
-#               %td #{equip.detail_id}
-#               %td #{equip.expiry_date}
-#       %br
-#
-#     - if @data["equipment"]
-#       -# Serial product list
-#       %h3 Items
-#       %table.table-hover{}
-#         %thead
-#           %tr
-#             %th{:style => "width: 33%"} Serial ID
-#             %th{:style => "width: 33%"} Name
-#             %th{:style => "width: 33%"} Availability
-#         %tbody
-#           - @data["equipment"].detail.each do |equip|
-#             %tr{:onclick => "window.location='#{equip.equipment_id}/#{equip.detail_id}';"}
-#               %td #{equip.detail_id}
-#               %td #{equip.equipment.name}
-#               %td #{equip.available}
-#       %br
-#
-#
-#     - if @data["upc_exp_tableA"]
-#       -# Upcoming Expiries table
-#       %h3 Upcoming Expiries
-#       %table.table-hover{}
-#         %thead
-#           %tr
-#             %th{:style => "width: 33%"} Product ID
-#             %th{:style => "width: 33%"} Serial ID
-#             %th{:style => "width: 33%"} Name
-#         %tbody
-#           - @data["upc_exp_tableA"].each do |equip|
-#             - if @searched
-#               %tr{:onclick => "window.location='#{equip.equipment_id}';"}
-#                 %td #{equip.equipment_id}
-#                 %td #{equip.detail_id}
-#                 %td #{@equipment.where(id: equip.equipment_id)[0].name}
-#             - else
-#               %tr{:onclick => "window.location='/finances/#{equip.equipment_id}/#{equip.detail_id}';"}
-#                 %td #{equip.equipment_id}
-#                 %td #{equip.detail_id}
-#                 %td #{@equipment.where(id: equip.equipment_id)[0].name}
-#       %br
-#       -# Full table
-#       %h3 All itemsAll items
-#       %table.table-hover{}
-#         %thead
-#           %tr
-#             %th{:style => "width: 33%"} Product ID
-#             %th{:style => "width: 33%"} Name
-#             %th{:style => "width: 33%"} # available
-#         %tbody
-#           - @equipment.each do |equip|
-#             - if @searched
-#               %tr{:onclick => "window.location='#{equip.id}';"}
-#                 %td #{equip.id}
-#                 %td #{equip.name}
-#                 %td #{@detail.where(equipment_id: equip.id, available: true).size}
-#             - else
-#               %tr{:onclick => "window.location='/finances/#{equip.id}';"}
-#                 %td #{equip.id}
-#                 %td #{equip.name}
-#                 %td #{@detail.where(equipment_id: equip.id, available: true).size}
-#       %br
-#
-#     - if params[:s_id]
-#       -# %button.btn.btn-warning{:href => "/finances/#{@data["detail"].equipment_id}", :type => "button"} Warning
-#       %a.btn.btn-warning{:href => "/finances/#{@data["detail"].equipment_id}", :role => "button"} Back to Equipment
-#     - if params[:p_id]
-#       %a.btn.btn-warning{:href => "/finances", :role => "button"} Back to Overview