config/routes.rb
Rails.application.routes.draw do

  resources :service_reminders
  resources :pdf_types
  resources :locations
  resources :reports
  resources :logs
  resources :detail_requests
  resources :equipment_pdfs
  mount EpiCas::Engine, at: "/"
  devise_for :accounts

  get 'finances/index'
  # get 'finances/show'

  resources :accounts do
    post :search, on: :collection
  end
  resources :audits
  resources :pdfs do
    get :show_pdf, on: :member
  end
  resources :equipment do
    get :show_image, on: :member
    post :search, on: :collection
  end
  resources :pdfs do
    post :search, on: :collection
  end
  resources :locations do
    post :search, on: :collection
  end

  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "pages#home"

  #get :splash, to: 'pages#splash'
  #get :borrowing, to: 'pages#borrowing'
  #get :returning, to: 'pages#returning'
  #get :home, to: "pages#home"
  get :view_items, to: 'equipment#index'
  get :new_equipment, to: 'equipment#new'
  # get :add_equipment, to: 'pages#add'
  # get :view_account_archive, to: 'pages#view_account_archive'
  # get :view_item_archive, to: 'pages#view_item_archive'
  # get :view_pdf, to: 'pages#view_pdf'
  # get :tables, to: 'pages#tables'
  # get :user, to: 'pages#user'
  # get :item, to: 'pages#item'
  # get :add_account, to: 'pages#add_account'
  # get :view_laboratories, to: 'pages#view_laboratories'
  # get :laboratory, to: 'pages#laboratory'
  get 'details/new/:id', to: 'details#new'
  get 'details/toggle_is_archived/:id', to: 'details#toggle_is_archived'
  get 'detail_requests/approve/:id', to: 'detail_requests#approve'
  get 'detail_requests/approve_equipment/:id', to: 'detail_requests#approve_equipment'
  get 'detail_requests/remove_equipment/:id', to: 'detail_requests#deny_equipment'
  get 'detail_requests/approve_extension/:id', to: 'detail_requests#approve_extension'
  get 'detail_requests/reject_extension/:id', to: 'detail_requests#reject_extension'
  get 'reports/new/:a_id', to: 'reports#new'
  get 'reports', to: 'reports#index'
  get 'audits/new/:s_id', to: 'audits#new'
  get 'trainings/add_equipment/:p_id/:t_id', to: 'trainings#add_equipment'
  get 'trainings/add_equipment/:p_id', to: 'trainings#add_equipment'
  get 'trainings/add_account/:a_id/:t_id', to: 'trainings#add_account'
  get 'trainings/add_account/:a_id', to: 'trainings#add_account'
  get 'trainings/remove_account/:id', to: 'trainings#remove_account'
  get 'trainings/remove_equipment/:id', to: 'trainings#remove_equipment'
  get 'pdfs/add_equipment/:e_id/:p_id', to: 'pdfs#add_equipment'
  get 'pdfs/add_equipment/:e_id', to: 'pdfs#add_equipment'
  get 'finances', to: 'finances#index'do
    post :search, on: :collection
  end
  resources :trainings
  resources :details
  get 'finances/:p_id', to: 'finances#index'
  get 'finances/:p_id/:s_id', to: 'finances#index'
  get :backup, to: 'backup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/equipment_pdf.rb
# == Schema Information
#
# Table name: equipment_pdfs
#
#  id           :integer          not null, primary key
#  equipment_id :integer
#  pdf_id       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class EquipmentPdf < ApplicationRecord
  belongs_to :equipment
  belongs_to :pdf
  def self.to_csv(make)
    attributes = %w{id equipment_id pdf_id created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      EquipmentPdf.all.each do |e|
        csv << attributes.map{ |attr| e.send(attr) }
      end
    end
  end
end

app/controllers/equipment_pdfs_controller.rb
class EquipmentPdfsController < ApplicationController
  before_action :set_equipment_pdf, only: [:show, :edit, :update, :destroy]
  
  authorize_resource

  # GET /equipment_pdfs
  def index
    @equipment_pdfs = EquipmentPdf.all
  end

  # GET /equipment_pdfs/1
  def show
  end

  # GET /equipment_pdfs/new
  def new
    @equipment_pdf = EquipmentPdf.new
  end

  # GET /equipment_pdfs/1/edit
  def edit
  end

  # POST /equipment_pdfs
  def create
    @equipment_pdf = EquipmentPdf.new(equipment_pdf_params)

    if @equipment_pdf.save
      redirect_to @equipment_pdf, notice: 'Equipment pdf was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /equipment_pdfs/1
  def update
    if @equipment_pdf.update(equipment_pdf_params)
      redirect_to @equipment_pdf, notice: 'Equipment pdf was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /equipment_pdfs/1
  def destroy
    @equipment_pdf.destroy
    redirect_to equipment_pdfs_url, notice: 'Equipment pdf was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment_pdf
      @equipment_pdf = EquipmentPdf.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def equipment_pdf_params
      params.require(:equipment_pdf).permit(:equipment_id, :pdf_id)
    end
end

app/helpers/equipment_pdfs_helper.rb
module EquipmentPdfsHelper
end

app/views/equipment_pdfs/_form.html.haml
= simple_form_for(@equipment_pdf) do |f|
  = f.error_notification

  .form-inputs.form-horizontal
    .form-group
      .control-label.col-sm-4
        = f.label "Equipment: "
      .col-sm-8
        = f.input :equipment_id, :label => false
    .form-group
      .control-label.col-sm-4
        = f.label "PDF: "
      .col-sm-8
        = f.input :pdf_id, :label => false

  .form-actions
    .form-group
      .col-sm-12
        = f.button :submit

app/views/equipment_pdfs/edit.html.haml
.container
  %h1 Editing equipment_pdf
  .row
    .col-sm-8.col-sm-offset-2
      = render 'form'
  %br
  .row
    -# = link_to 'Show', @equipment_pdf
    %a.btn{:href => "/equipment_pdfs/#{@equipment_pdf.equipment_id}", :role => "button"} Show
    -# = link_to 'Back', equipment_pdfs_path
    %a.btn{:href => "/equipment_pdfs", :role => "button"} Back

app/views/equipment_pdfs/index.html.haml
.container
  %h1 Listing Equipment PDFs

  %table.table-hover
    %thead
      %tr
        %th Equipment
        %th Pdf
        %th
        %th
        %th

    %tbody
      - @equipment_pdfs.each do |equipment_pdf|
        %tr
          %td= equipment_pdf.equipment_id
          %td= equipment_pdf.pdf_id
          %td= link_to 'Show', equipment_pdf
          %td= link_to 'Edit', edit_equipment_pdf_path(equipment_pdf)
          %td= link_to 'Destroy', equipment_pdf, method: :delete, data: { confirm: 'Are you sure?' }

  %br

  -# = link_to 'New Equipment pdf', new_equipment_pdf_path
  %a.btn{:href => "/equipment_pdfs/new", :role => "button"} New Equipment PDF

app/views/equipment_pdfs/new.html.haml
- content_for :title, "NEW EQUIPMENT PDF"
.container
  %h1 New Equipment PDF
  %br
  .row
    .col-sm-8.col-sm-offset-2
      = render 'form'
  %br
  .row
    -# = link_to 'Back', equipment_pdfs_path
    %a.btn{:href => "/equipment_pdfs", :role => "button"} Back

app/views/equipment_pdfs/show.html.haml
.container
  %p#notice= notice
  %h1 PDF Associations
  %p
    %b Equipment:
    = @equipment_pdf.equipment_id
  %p
    %b Pdf:
    = @equipment_pdf.pdf_id

  -# = link_to 'Edit', edit_equipment_pdf_path(@equipment_pdf)
  %a.btn{:href => "/equipment_pdfs/#{@equipment_pdf.equipment_id}/edit", :role => "button"} Edit
  -# = link_to 'Back', equipment_pdfs_path
  %a.btn{:href => "/equipment_pdfs", :role => "button"} Back