config/routes.rb
Rails.application.routes.draw do

  resources :service_reminders
  resources :pdf_types
  resources :locations
  resources :reports
  resources :logs
  resources :detail_requests
  resources :equipment_pdfs
  mount EpiCas::Engine, at: "/"
  devise_for :accounts

  get 'finances/index'
  # get 'finances/show'

  resources :accounts do
    post :search, on: :collection
  end
  resources :audits
  resources :pdfs do
    get :show_pdf, on: :member
  end
  resources :equipment do
    get :show_image, on: :member
    post :search, on: :collection
  end
  resources :pdfs do
    post :search, on: :collection
  end
  resources :locations do
    post :search, on: :collection
  end

  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "pages#home"

  #get :splash, to: 'pages#splash'
  #get :borrowing, to: 'pages#borrowing'
  #get :returning, to: 'pages#returning'
  #get :home, to: "pages#home"
  get :view_items, to: 'equipment#index'
  get :new_equipment, to: 'equipment#new'
  # get :add_equipment, to: 'pages#add'
  # get :view_account_archive, to: 'pages#view_account_archive'
  # get :view_item_archive, to: 'pages#view_item_archive'
  # get :view_pdf, to: 'pages#view_pdf'
  # get :tables, to: 'pages#tables'
  # get :user, to: 'pages#user'
  # get :item, to: 'pages#item'
  # get :add_account, to: 'pages#add_account'
  # get :view_laboratories, to: 'pages#view_laboratories'
  # get :laboratory, to: 'pages#laboratory'
  get 'details/new/:id', to: 'details#new'
  get 'details/toggle_is_archived/:id', to: 'details#toggle_is_archived'
  get 'detail_requests/approve/:id', to: 'detail_requests#approve'
  get 'detail_requests/approve_equipment/:id', to: 'detail_requests#approve_equipment'
  get 'detail_requests/remove_equipment/:id', to: 'detail_requests#deny_equipment'
  get 'detail_requests/approve_extension/:id', to: 'detail_requests#approve_extension'
  get 'detail_requests/reject_extension/:id', to: 'detail_requests#reject_extension'
  get 'reports/new/:a_id', to: 'reports#new'
  get 'reports', to: 'reports#index'
  get 'audits/new/:s_id', to: 'audits#new'
  get 'trainings/add_equipment/:p_id/:t_id', to: 'trainings#add_equipment'
  get 'trainings/add_equipment/:p_id', to: 'trainings#add_equipment'
  get 'trainings/add_account/:a_id/:t_id', to: 'trainings#add_account'
  get 'trainings/add_account/:a_id', to: 'trainings#add_account'
  get 'trainings/remove_account/:id', to: 'trainings#remove_account'
  get 'trainings/remove_equipment/:id', to: 'trainings#remove_equipment'
  get 'pdfs/add_equipment/:e_id/:p_id', to: 'pdfs#add_equipment'
  get 'pdfs/add_equipment/:e_id', to: 'pdfs#add_equipment'
  get 'finances', to: 'finances#index'do
    post :search, on: :collection
  end
  resources :trainings
  resources :details
  get 'finances/:p_id', to: 'finances#index'
  get 'finances/:p_id/:s_id', to: 'finances#index'
  get :backup, to: 'backup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id          :integer          not null, primary key
#  audit_id    :integer
#  description :text
#  fixing_logs :text
#  resolved_by :text
#  urgency     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Report < ActiveRecord::Base
  belongs_to :audit
  attr_accessor :extend_lifetime
  attr_accessor :request_deactivation
  def self.to_csv(make)
    attributes = %w{id audit_id description fixing_logs resolved_by urgency created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      Report.all.each do |e|
        csv << attributes.map{ |attr| e.send(attr) }
      end
    end
  end
  # validates :fixing_logs, :presence => true
  # validates :extend_lifetime, :numericality => true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  authorize_resource

  # GET /reports
  def index
    @reports = Report.order('urgency DESC').order('created_at').where(resolved_by: "") + Report.order('urgency DESC').order('created_at').where.not(resolved_by: "")
  end

  # GET /reports/1
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
    puts params[:id]
    puts "***************"
    @detail = Report.find(params[:id]).audit.detail
  end

  # POST /reports
  def create
    d = Audit.find(params[:report][:audit_id]).detail
    @report = Report.new(report_new_params)
    @report.resolved_by = ""
    if @report.save

      ReportMailer.notify_tech(@report, Account.system_tech, d).deliver_now
      redirect_to @report, notice: 'Report was successfully created.'
    else
      render :new
    end
  end


  # PATCH/PUT /reports/1
  def update
    audit_id = Report.find(report_update_params[:id]).audit_id
    if(report_update_params[:request_deactivation])
      @detail_request = DetailRequest.create({detail_id: Audit.find(audit_id).detail_id, archived_new_value: false})
    end
    d = Audit.find(audit_id).detail

    if current_account.admin?
      d.update(life_expectancy: d.life_expectancy + report_update_params[:extend_lifetime].to_i)
    else
      LifespanAlteration.create(detail_id: d[:id], extension: report_update_params[:extend_lifetime].to_i)
    end

    if @report.update(report_update_params)
      redirect_to "/reports", notice: 'Report was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_url, notice: 'Report was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def report_new_params
      params.require(:report).permit(:audit_id, :description, :urgency)
    end
    def report_update_params
      params.require(:report).permit(:id, :fixing_logs, :resolved_by, :urgency, :extend_lifetime, :request_deactivation)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= simple_form_for(@report) do |f|
  = f.error_messages
  = f.error_notification

  .form-inputs

    = f.input :id, :input_html => {:value => params[:id]}, :readonly => true, :as => :hidden
    = f.input :fixing_logs
    = f.input :resolved_by, :input_html => { :value => current_account.id }, :readonly => true, :as => :hidden
    = f.input :extend_lifetime, :input_html => { :value => 0 }
    = f.input :request_deactivation, as: :boolean, checked_value: true, unchecked_value: false


  .form-actions
    = f.button :submit

app/views/reports/edit.html.haml
.container
  %h1 Editing report for #{@detail.equipment.name} : #{@detail.detail_id}

  = render 'form'

  = link_to 'Show', @report
  \|
  = link_to 'Back', reports_path

app/views/reports/index.html.haml
- content_for :title, "VIEW_REPORTS"
.container
  %h1 Listing reports

  %table.table-hover{}
    %thead
      %tr
        %th Product name : ID
        %th Loan ID
        %th Description
        %th Fixing logs
        %th Resolved by
        %th Urgency

    %tbody
      - @reports.each do |report|
        %tr{:onclick => "window.location='/reports/#{report[:id]}/edit';"}
          %td #{report.audit.equipment.name} : #{report.audit.detail.detail_id}
          %td= report.audit_id
          %td= report.description
          %td= report.fixing_logs
          %td= report.resolved_by
          %td= report.urgency

app/views/reports/new.html.haml
.container
  %h1 New report
  %br
  .row
    .col-sm-8.col-sm-offset-2
      = simple_form_for(@report) do |f|
        = f.error_notification

        .form-inputs.form-horizontal
          = f.input :audit_id, :input_html => {:value => params[:a_id]}, :as => :hidden
          .form-group
            .control-label.col-sm-4
              = f.label "Description: "
            .col-sm-8
              = f.input :description, :label => false
          .form-group
            .control-label.col-sm-4
              = f.label "Severity Rating: "
            .col-sm-8.text-left
              = f.select :urgency, ['3', '2', '1']

        .form-actions
          .form-group
            .col-sm-12
              = f.button :submit

  %br

  %a.btn{:href => "/accounts", :role => "button"} Back to Accounts

  -#
  -# = link_to 'Back', reports_path

app/views/reports/show.html.haml
%p#notice= notice
%br
%br
%br
%p
  %b Loan:
  = @report.audit_id
%p
  %b Description:
  = @report.description
-# %p
-#   %b Fixing logs:
-#   = @report.fixing_logs
-# %p
-#   %b Resolved by:
-#   = @report.resolved_by

-# = link_to 'Edit', edit_report_path(@report)
-# \|
%a.btn{:href => "/reports", :role => "button"} See the Report
%a.btn{:href => "/reports/#{@report.id}/edit", :role => "button"} Edit Report